name: Feature Branch

on:
  push:
    branches:
      - "feature/**"

permissions:
  id-token: write
  contents: read

jobs:
  check-ui-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: check
        run: |
          if git diff --name-only origin/main...HEAD | grep '^ui/'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

  terraform-deploy:
    runs-on: ubuntu-latest
    outputs:
      s3_cv_bucket: ${{ steps.tf.outputs.s3_cv_bucket }}
      base_api_url: ${{ steps.tf.outputs.base_api_url }}
      cv_updates_topic_arn: ${{ steps.tf.outputs.cv_updates_topic_arn }}
      website_url: ${{ steps.tf.outputs.website_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/load-env
        with:
          file: ./.github/env/dev.env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Package Lambdas
        working-directory: ui
        run: |
          for dir in lambda/*/; do
            echo "Packaging $dir"

            (
              cd "$dir"
              rm -f lambda.zip
              zip -r lambda.zip .
            )
          done

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=tf-state-regdeg90" \
            -backend-config="key=cv-website/${{ env.ENVIRONMENT }}.tfstate" \
            -backend-config="region=eu-north-1"

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var-file="${{ env.ENVIRONMENT }}.tfvars"

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var-file="${{ env.ENVIRONMENT }}.tfvars"

      - name: Set TF Outputs to ENV
        id: tf
        working-directory: terraform
        run: |
          echo "s3_cv_bucket=$(terraform output -raw bucket_name)" >> "$GITHUB_OUTPUT"
          echo "base_api_url=$(terraform output -raw base_api_url)" >> "$GITHUB_OUTPUT"
          echo "cv_updates_topic_arn=$(terraform output -raw cv_updates_topic_arn)" >> "$GITHUB_OUTPUT"
          echo "website_url=$(terraform output -raw website_url)" >> "$GITHUB_OUTPUT"

  build-cv-pdf:
    needs:
      - check-ui-changes
      - terraform-deploy
    if: needs.check-ui-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: CV.tex
          working_directory: ui
          latexmk_use_xelatex: true

      - uses: ./.github/actions/load-env
        with:
          file: ./.github/env/dev.env

      - name: Replace JS Config
        run: |
          sed -i \
            "s|__BASE_API_URL__|${{ needs.terraform-deploy.outputs.base_api_url }}|g" \
            ui/js/config.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Upload website to S3
        run: |
          aws s3 sync ui/ s3://${{ needs.terraform-deploy.outputs.s3_cv_bucket }}/ --delete

      - name: Notify CV subscribers
        run: |
          aws sns publish \
            --topic-arn "${{ needs.terraform-deploy.outputs.cv_updates_topic_arn }}" \
            --subject "Reuben's CV has been updated" \
            --message "My CV website has been updated. View the latest version at ${{ needs.terraform-deploy.outputs.website_url }}"